### ISSUE TITLE
Make user fails on Ubuntu 18.04.3 LTS

### ISSUE THREAD

**Issue by BeFlo** [SEL4PROJ/seL4-CAmkES-L4v-dockerfiles#12]
When running make user command inside the seL4-CAmkES-L4v-dockerfiles folder the following error occurs on Step 3. "rm: cannot remove '/var/lib/apt/lists/*': No such file or directory". (Full error message below). I am not sure 

System Setup
Ubuntu 18.04.3 LTS
Kernel version: 5.0.0-37-generic x86_64 I

Step 3/3 : RUN rm -r /var/lib/apt/lists/*     && apt-get update -q     && apt-get install -y --no-install-recommends         cowsay         sudo     && apt-get clean autoclean     && apt-get autoremove --yes     && rm -rf /var/lib/{apt,dpkg,cache,log}/
 ---> Running in e66d8cad4c49
rm: cannot remove '/var/lib/apt/lists/*': No such file or directory
Removing intermediate container e66d8cad4c49
The command '/bin/sh -c rm -r /var/lib/apt/lists/*     && apt-get update -q     && apt-get install -y --no-install-recommends         cowsay         sudo     && apt-get clean autoclean     && apt-get autoremove --yes     && rm -rf /var/lib/{apt,dpkg,cache,log}/' returned a non-zero code: 1
Makefile:160: recipe for target 'build_user' failed

I am not sure if this a real error.
Thanks & Regards
BeFlo

**Comment by dymil** [comment]
I'm having the same issue on Debian buster (10.0) on Windows, running Docker via [this guide for WSL](https://nickjanetakis.com/blog/setting-up-docker-for-windows-and-wsl-to-work-flawlessly).

**Comment by LukeMondy** [comment]
Sorry for the delay, the holiday period slows everything down.

I've put forward a fix for this internally, which may take a day or so to push out. The fix is to modify `extras.dockerfile` to look like this:

```
RUN apt-get update -q \
    && apt-get install -y --no-install-recommends \
        # Add more dependencies here
        cowsay \
        sudo 
```
Let us know if that helps!

**Comment by dymil** [comment]
Making that change got me past the initial error described in the original post, but now when trying to make the user_run target, I get the following error:

> docker: Error response from daemon: OCI runtime create failed: container_linux.go:346: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"/etc/localtime\\\" to rootfs \\\"/var/lib/docker/overlay2/778f3fba720f560454896e05cb92f05561813c5d29d5140fa16bcc426728bc3e/merged\\\" at \\\"/var/lib/docker/overlay2/778f3fba720f560454896e05cb92f05561813c5d29d5140fa16bcc426728bc3e/merged/usr/share/zoneinfo/UCT\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type.
make: *** [Makefile:113: user_run] Error 125

I'm not sure if it's related.

**Comment by LukeMondy** [comment]
I'm guessing it's related to running under WSL.

This line in particular seems to be causing the issue: https://github.com/SEL4PROJ/seL4-CAmkES-L4v-dockerfiles/blob/ecdfd80ce2a32aa278a2b870e4a60c56baad2c19/Makefile#L120

You can delete it, and see if it helps. It's just a quality-of-life thing, so the container has the same time as your host machine. That _should_ be the only issue, but we haven't tried the containers on WSL at all, so there may be other issues.

**Comment by BeFlo** [comment]
Same issue for me after i have deleted line 120 and line 132.

**Comment by LukeMondy** [comment]
There are now two issues: the original, and the issue reported by @dymil :

> > docker: Error response from daemon: OCI runtime create failed: container_linux.go:346: starting container process caused "process_linux.go:449: container init caused "rootfs_linux.go:58: mounting \"/etc/localtime\" to rootfs \"/var/lib/docker/overlay2/778f3fba720f560454896e05cb92f05561813c5d29d5140fa16bcc426728bc3e/merged\" at \"/var/lib/docker/overlay2/778f3fba720f560454896e05cb92f05561813c5d29d5140fa16bcc426728bc3e/merged/usr/share/zoneinfo/UCT\" caused \"not a directory\""": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type.
> > make: *** [Makefile:113: user_run] Error 125

Have you also applied this fix? https://github.com/SEL4PROJ/seL4-CAmkES-L4v-dockerfiles/issues/12#issuecomment-571345839

**Comment by BeFlo** [comment]
Cool, I got it working now. Thanks for the support

**Comment by LukeMondy** [comment]
Great!
