### ISSUE TITLE
"make user" broken

### ISSUE THREAD

**Issue by johnhansen97** [SEL4PROJ/seL4-CAmkES-L4v-dockerfiles#13]
Commit [ac8254](https://github.com/SEL4PROJ/seL4-CAmkES-L4v-dockerfiles/commit/ac8254296d09a261160a1652ffeb1f1e296bf917) apparently breaks the 'make user' command because the Dockerfiles are now in a different directory.
<pre><font color="#8AE234"><b>john@john-VirtualBox</b></font>:<font color="#729FCF"><b>~/Documents/cpre440x/sel4-CAmkES-L4v-dockerfiles</b></font>$ make user
# Figure out if any trustworthy systems docker images are potentially too old
docker build --force-rm=true \
	--build-arg=USER_BASE_IMG=trustworthysystems/camkes \
	-f extras.dockerfile \
	-t extras \
	.
unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /home/john/Documents/cpre440x/sel4-CAmkES-L4v-dockerfiles/extras.dockerfile: no such file or directory
Makefile:160: recipe for target &apos;build_user&apos; failed
make: *** [build_user] Error 1
</pre>
The problem does not exist in the previous commit.

**Comment by LukeMondy** [comment]
Hi,

Thanks for reporting this! Unfortunately a silly mistake on my part with the last commit.

I've fixed it internally, and it should push out later today or tomorrow.

If you'd like to fix it immediately on your computer, you need to edit:
https://github.com/SEL4PROJ/seL4-CAmkES-L4v-dockerfiles/blob/02a98808423673568179b820ea66abb62ecdbba0/Makefile#L162
to read:
```
	-f dockerfiles/extras.dockerfile \
```
and also:
https://github.com/SEL4PROJ/seL4-CAmkES-L4v-dockerfiles/blob/02a98808423673568179b820ea66abb62ecdbba0/Makefile#L169
to read:
```
	-f dockerfiles/user.dockerfile \
```

**Comment by johnhansen97** [comment]
Excellent. Thank you!

**Comment by LukeMondy** [comment]
Fixed in https://github.com/SEL4PROJ/seL4-CAmkES-L4v-dockerfiles/commit/d934fa11f9087d9dd4072817d46406904e96b81d
